version: '3.8'

services:
  backend:
    build: ./Backend
    # Ports không cần thiết nữa vì Nginx sẽ xử lý
    volumes:
      - ./Backend/uploads_data:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./Frontend
    # Ports không cần thiết nữa vì Nginx sẽ xử lý
    volumes:
      - ./Frontend/src:/app/src
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  # Thêm service Nginx
  nginx:
    image: nginx:alpine
    ports:
      # Ánh xạ cổng 80 của máy host vào cổng 80 của Nginx
      - "21030:80"
    volumes:
      # Mount file cấu hình Nginx vào container
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

networks:
  default:
    driver: bridge